/**
 * Generate src/lib/icons.generated.ts containing pre-rendered SVG strings for the curated icon set.
 * Keeping this static avoids bundling the entire lucide-react (and react-dom/server) into the
 * public client bundle. Re-run with `npx tsx scripts/gen-icons.ts` if you change the curated list.
 */

import * as Icons from 'lucide-react';
import { renderToString } from 'react-dom/server';
import { createElement } from 'react';
import { writeFileSync } from 'node:fs';

const CURATED = [
  'crown', 'shield', 'sword', 'castle', 'scroll', 'feather', 'flag',
  'book', 'book-open', 'library', 'graduation-cap', 'gavel', 'church',
  'map-pin', 'map', 'compass', 'mountain', 'tree-pine', 'home', 'building',
  'user', 'users', 'baby',
  'calendar', 'calendar-days', 'clock', 'hourglass',
  'star', 'sparkles', 'gem', 'award', 'trophy',
  'circle', 'square', 'triangle', 'heart',
  'cross',
  'external-link', 'link', 'mail', 'phone', 'message-circle',
  'eye', 'info', 'alert-triangle', 'check-circle', 'x-circle',
  'arrow-right', 'arrow-left', 'arrow-up', 'arrow-down',
  'image', 'file-text', 'globe', 'flame', 'droplets', 'snowflake', 'sun', 'moon',
];

function pascalCase(name: string): string {
  return name
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

const out: Record<string, string> = {};
let missing = 0;
for (const name of CURATED) {
  const Component = (Icons as unknown as Record<string, React.ComponentType<{ size: number }>>)[
    pascalCase(name)
  ];
  if (!Component) {
    console.warn(`Missing icon: ${name}`);
    missing++;
    continue;
  }
  // Use size=24 (lucide default) - we'll scale via width/height attrs in hydrator
  const svg = renderToString(createElement(Component, { size: 24 }));
  out[name] = svg;
}

const fileContent = `// Auto-generated by scripts/gen-icons.ts. Do not edit by hand.
// Re-run \`npx tsx scripts/gen-icons.ts\` to regenerate.

export const ICON_SVGS: Record<string, string> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync('src/lib/icons.generated.ts', fileContent);
console.log(`✓ Wrote ${CURATED.length - missing} icons to src/lib/icons.generated.ts`);
